# Generated by Django 5.1.7 on 2025-06-26 00:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('rows', models.PositiveIntegerField()),
                ('columns', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=30, unique=True)),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_flight', 'In flight'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='home.airplane')),
                ('users', models.ManyToManyField(blank=True, related_name='managed_flights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('row', models.PositiveIntegerField()),
                ('column', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('economy', 'Economy'), ('premium', 'Premium'), ('business', 'Business')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied')], default='available', max_length=20)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='home.airplane')),
            ],
            options={
                'unique_together': {('airplane', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('reservation_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation_code', models.CharField(max_length=20, unique=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='home.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='home.passenger')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='home.seat')),
            ],
            options={
                'unique_together': {('flight', 'passenger')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('canceled', 'Canceled')], default='issued', max_length=20)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='home.reservation')),
            ],
        ),
    ]
