# Generated by Django 5.2.3 on 2025-08-12 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='airplane',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airplane',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='users',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='passenger',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='reservation',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='Airplane',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='Seat',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
